// Generated by DCL (Differentiable Cryptographic Language) Compiler
// Backend: Zama tfhe-rs

use tfhe::prelude::*;
use tfhe::{FheUint64, FheBool, ServerKey};

pub struct verify_adultInputs {
    pub cred_age: FheUint64,
    pub cred_id_hash: FheUint64,
    pub threshold: FheUint64,
}

pub fn verify_adult(
    inputs: &verify_adultInputs,
    server_key: &ServerKey,
) -> FheUint64 {
    let mut n_0 = inputs.cred_age.clone();
    let mut n_1 = inputs.cred_id_hash.clone();
    let mut n_2 = inputs.threshold.clone();
    let mut n_3 = &n_0 - &n_2;
    let cond_range_4 = n_3.lt(u64::MAX);
    let one_const_4 = FheUint64::try_encrypt_trivial(1u64, server_key).unwrap();
    let zero_const_4 = FheUint64::try_encrypt_trivial(0u64, server_key).unwrap();
    let mut n_4 = cond_range_4.select(&one_const_4, &zero_const_4);
    let mut n_5 = FheUint64::try_encrypt_trivial(1, server_key).unwrap();
    // Assertion check node 6
    // WARNING: Poseidon is algebraically complex in FHE; using stub
    let mut n_7 = n_0.clone();
    let mut n_8 = &n_7 - &n_1;
    let cond_zero_9 = n_8.eq(0u64);
    let one_const_9 = FheUint64::try_encrypt_trivial(1u64, server_key).unwrap();
    let zero_const_9 = FheUint64::try_encrypt_trivial(0u64, server_key).unwrap();
    let mut n_9 = cond_zero_9.select(&one_const_9, &zero_const_9);
    n_9
}
