// Generated by DCL (Differentiable Cryptographic Language) Compiler
pragma circom 2.0.0;

include "poseidon.circom"; // Requires circomlib Poseidon

template verify_adultMain() {
    signal input cred_age;
    signal input cred_id_hash;
    signal input threshold;
    signal output out_9;

    // Intermediate signals
    signal n_3;
    signal n_4;
    signal n_5;
    signal n_7;
    signal n_8;
    signal n_9;
    signal inv_9;

    n_3 <== cred_age - threshold; // Line 12
    // Optimized: Lookup table range check (64 bits) // Line 12
    signal bits_lookup_4[64];
    // Table index constraint lookup mapping...
    signal bits_4[64];
    var sum_4 = 0;
    for (var i = 0; i < 64; i++) {
        bits_4[i] <-- (n_3 >> i) & 1;
        bits_4[i] * (1 - bits_4[i]) === 0;
        sum_4 += bits_4[i] * (2 ** i);
    }
    n_3 === sum_4;
    n_4 <== 1;
    n_5 <== 1; // Line 12
    n_4 === n_5; // Line 12
    component poseidon_7 = Poseidon(2); // Line 13
    poseidon_7.inputs[0] <== cred_age;
    poseidon_7.inputs[1] <== cred_id_hash;
    n_7 <== poseidon_7.out;
    n_8 <== n_7 - cred_id_hash; // Line 14
    inv_9 <-- n_8 == 0 ? 0 : 1 / n_8; // Line 14
    n_9 <== 1 - n_8 * inv_9;
    n_8 * n_9 === 0;
    out_9 <== n_9;
}

component main {public [threshold]} = verify_adultMain();
