// Generated by DCL (Differentiable Cryptographic Language) Compiler
pragma circom 2.0.0;

include "poseidon.circom"; // Requires circomlib Poseidon

template compute_interestMain() {
    signal input principal;
    signal input rate;
    signal output out_4;

    // Intermediate signals
    signal n_2;
    signal n_3;
    signal n_4;

    n_2 <== principal * rate;
    n_3 <== 65536;
    n_4 <-- n_2 / n_3;
    n_4 * n_3 === n_2;
    out_4 <== n_4;
}

component main = compute_interestMain();
