// Generated by DCL (Differentiable Cryptographic Language) Compiler
// Backend: Zama tfhe-rs

use tfhe::prelude::*;
use tfhe::{FheUint64, FheBool, ServerKey};

pub struct computeInputs {
    pub a: FheUint64,
    pub b: FheUint64,
}

pub fn compute(
    inputs: &computeInputs,
    server_key: &ServerKey,
) -> FheUint64 {
    let n_0 = inputs.a.clone();
    let n_1 = inputs.b.clone();
    let n_2 = &n_0 * &n_1;
    let n_3 = &n_2 + &n_0;
    n_3
}
