// Generated by DCL (Differentiable Cryptographic Language) Compiler
pragma circom 2.0.0;

include "poseidon.circom"; // Requires circomlib Poseidon

template verify_leaf_and_merkleMain() {
    signal input leaf;
    signal input sibling0;
    signal input root;
    signal input bound;
    signal output out_12;

    // Intermediate signals
    signal n_4;
    signal n_5;
    signal n_6;
    signal n_7;
    signal n_8;
    signal n_10;
    signal n_11;
    signal n_12;
    signal inv_12;

    n_4 <== bound - leaf;
    n_5 <== 1;
    n_6 <== n_4 - n_5;
    // Optimized: Lookup table range check (64 bits)
    signal bits_lookup_7[64];
    // Table index constraint lookup mapping...
    signal bits_7[64];
    var sum_7 = 0;
    for (var i = 0; i < 64; i++) {
        bits_7[i] <-- (n_6 >> i) & 1;
        bits_7[i] * (1 - bits_7[i]) === 0;
        sum_7 += bits_7[i] * (2 ** i);
    }
    n_6 === sum_7;
    n_7 <== 1;
    n_8 <== 1;
    n_7 === n_8;
    component poseidon_10 = Poseidon(2);
    poseidon_10.inputs[0] <== leaf;
    poseidon_10.inputs[1] <== sibling0;
    n_10 <== poseidon_10.out;
    n_11 <== n_10 - root;
    inv_12 <-- n_11 == 0 ? 0 : 1 / n_11;
    n_12 <== 1 - n_11 * inv_12;
    n_11 * n_12 === 0;
    out_12 <== n_12;
}

component main {public [root, bound]} = verify_leaf_and_merkleMain();
