// Generated by DCL (Differentiable Cryptographic Language) Compiler
pragma circom 2.0.0;

include "poseidon.circom"; // Requires circomlib Poseidon

template verify_merkleMain() {
    signal input leaf;
    signal input path_0;
    signal input path_1;
    signal input path_2;
    signal input path_3;
    signal input root;
    signal output out_15;

    // Intermediate signals
    signal n_6;
    signal n_7;
    signal n_8;
    signal n_9;
    signal n_10;
    signal n_11;
    signal n_12;
    signal n_13;
    signal n_14;
    signal n_15;
    signal inv_15;

    n_6 <== 0;
    component poseidon_7 = Poseidon(2);
    poseidon_7.inputs[0] <== leaf;
    poseidon_7.inputs[1] <== path_0;
    n_7 <== poseidon_7.out;
    n_8 <== 1;
    component poseidon_9 = Poseidon(2);
    poseidon_9.inputs[0] <== n_7;
    poseidon_9.inputs[1] <== path_1;
    n_9 <== poseidon_9.out;
    n_10 <== 2;
    component poseidon_11 = Poseidon(2);
    poseidon_11.inputs[0] <== n_9;
    poseidon_11.inputs[1] <== path_2;
    n_11 <== poseidon_11.out;
    n_12 <== 3;
    component poseidon_13 = Poseidon(2);
    poseidon_13.inputs[0] <== n_11;
    poseidon_13.inputs[1] <== path_3;
    n_13 <== poseidon_13.out;
    n_14 <== n_13 - root;
    inv_15 <-- n_14 == 0 ? 0 : 1 / n_14;
    n_15 <== 1 - n_14 * inv_15;
    n_14 * n_15 === 0;
    out_15 <== n_15;
}

component main {public [root]} = verify_merkleMain();
