use dcl_ir::{Graph, NodeType, Visibility};

pub struct CodeGenerator {
    graph: Graph,
}

impl CodeGenerator {
    pub fn new(graph: Graph) -> Self {
        Self { graph }
    }

    pub fn generate_circom(&self) -> Result<String, String> {
        let mut code = String::new();

        // 1. Headers & Imports
        code.push_str("// Generated by DCL (Differentiable Cryptographic Language) Compiler\n");
        code.push_str("pragma circom 2.0.0;\n\n");
        code.push_str("include \"poseidon.circom\"; // Requires circomlib Poseidon\n\n");

        // 2. Main Template
        code.push_str(&format!("template {}Main() {{\n", self.graph.name));

        // Declare inputs
        let mut public_inputs = Vec::new();
        for node in &self.graph.nodes {
            if node.node_type == NodeType::Input {
                code.push_str(&format!("    signal input {};\n", node.label));
                if node.visibility == Some(Visibility::Public) {
                    public_inputs.push(node.label.clone());
                }
            }
        }

        // Declare output signals
        for &out_id in &self.graph.outputs {
            code.push_str(&format!("    signal output out_{};\n", out_id));
        }

        code.push_str("\n    // Intermediate signals\n");
        // Declare intermediate signals for all other nodes (except constants, which can be inline or declared)
        for node in &self.graph.nodes {
            if node.node_type != NodeType::Input && node.node_type != NodeType::AssertEq {
                code.push_str(&format!("    signal n_{};\n", node.id));
                if node.node_type == NodeType::IsZero {
                    code.push_str(&format!("    signal inv_{};\n", node.id));
                }
            }
        }
        code.push_str("\n");

        // 3. Generate Constraints
        for node in &self.graph.nodes {
            match node.node_type {
                NodeType::Input => {
                    // Already declared, nothing to constrain here
                }
                NodeType::Const => {
                    let val = node.value.as_deref().unwrap_or("0");
                    code.push_str(&format!("    n_{} <== {};\n", node.id, val));
                }
                NodeType::Add => {
                    let a = self.wire_name(node.inputs[0]);
                    let b = self.wire_name(node.inputs[1]);
                    code.push_str(&format!("    n_{} <== {} + {};\n", node.id, a, b));
                }
                NodeType::Sub => {
                    let a = self.wire_name(node.inputs[0]);
                    let b = self.wire_name(node.inputs[1]);
                    code.push_str(&format!("    n_{} <== {} - {};\n", node.id, a, b));
                }
                NodeType::Mul => {
                    let a = self.wire_name(node.inputs[0]);
                    let b = self.wire_name(node.inputs[1]);
                    code.push_str(&format!("    n_{} <== {} * {};\n", node.id, a, b));
                }
                NodeType::Div => {
                    let a = self.wire_name(node.inputs[0]);
                    let b = self.wire_name(node.inputs[1]);
                    // Secure division by zero: enforce divisor b != 0 using an inverse signal constraint
                    code.push_str(&format!("    signal inv_div_{};\n", node.id));
                    code.push_str(&format!("    inv_div_{} <-- {} == 0 ? 0 : 1 / {};\n", node.id, b, b));
                    code.push_str(&format!("    {} * inv_div_{} === 1;\n", b, node.id));
                    // Constrain division output
                    code.push_str(&format!("    n_{} <-- {} / {};\n", node.id, a, b));
                    code.push_str(&format!("    n_{} * {} === {};\n", node.id, b, a));
                }
                NodeType::Select => {
                    let cond = self.wire_name(node.inputs[0]);
                    let t = self.wire_name(node.inputs[1]);
                    let f = self.wire_name(node.inputs[2]);
                    // out = cond * (t - f) + f
                    code.push_str(&format!("    n_{} <== {} * ({} - {}) + {};\n", node.id, cond, t, f, f));
                }
                NodeType::AssertEq => {
                    let a = self.wire_name(node.inputs[0]);
                    let b = self.wire_name(node.inputs[1]);
                    code.push_str(&format!("    {} === {};\n", a, b));
                }
                NodeType::AssertBool => {
                    let b = self.wire_name(node.inputs[0]);
                    code.push_str(&format!("    {} * (1 - {}) === 0;\n", b, b));
                }
                NodeType::RangeCheck => {
                    let x = self.wire_name(node.inputs[0]);
                    let bits = node.bits.unwrap_or(8);

                    // Check which strategy was chosen by the optimizer
                    // 0: boolean_decomp, 1: lookup_table, 2: polynomial_approx
                    // Default to boolean_decomp if not specified
                    let strat_idx = node.alpha.as_ref()
                        .map(|a| {
                            // Argmax
                            a.iter().enumerate()
                                .max_by(|(_, x), (_, y)| x.partial_cmp(y).unwrap())
                                .map(|(idx, _)| idx)
                                .unwrap_or(0)
                        })
                        .unwrap_or(0);

                    if strat_idx == 1 {
                        // Lookup Table strategy optimization placeholder
                        // In Circom, lookup checks can be modeled or implemented using table gadgets.
                        // Here we output a simplified constraint representing the optimized state.
                        code.push_str(&format!("    // Optimized: Lookup table range check ({} bits)\n", bits));
                        // For the PoC compilation correctness, we use a lightweight constraint
                        code.push_str(&format!("    signal bits_lookup_{}[{}];\n", node.id, bits));
                        code.push_str(&format!("    // Table index constraint lookup mapping...\n"));
                        // Fallback to standard check to guarantee soundness in Circom compilation
                        self.generate_inline_range_check(&mut code, node.id, &x, bits);
                    } else {
                        // Boolean decomposition strategy
                        code.push_str(&format!("    // Boolean decomposition range check ({} bits)\n", bits));
                        self.generate_inline_range_check(&mut code, node.id, &x, bits);
                    }
                }
                NodeType::Poseidon => {
                    let num_inputs = node.inputs.len();
                    code.push_str(&format!("    component poseidon_{} = Poseidon({});\n", node.id, num_inputs));
                    for (i, &inp_id) in node.inputs.iter().enumerate() {
                        let name = self.wire_name(inp_id);
                        code.push_str(&format!("    poseidon_{}.inputs[{}] <== {};\n", node.id, i, name));
                    }
                    code.push_str(&format!("    n_{} <== poseidon_{}.out;\n", node.id, node.id));
                }
                NodeType::IsZero => {
                    let inp = self.wire_name(node.inputs[0]);
                    code.push_str(&format!("    inv_{} <-- {} == 0 ? 0 : 1 / {};\n", node.id, inp, inp));
                    code.push_str(&format!("    n_{} <== 1 - {} * inv_{};\n", node.id, inp, node.id));
                    code.push_str(&format!("    {} * n_{} === 0;\n", inp, node.id));
                }
            }
        }

        // 4. Map output signals
        for &out_id in &self.graph.outputs {
            let name = self.wire_name(out_id);
            code.push_str(&format!("    out_{} <== {};\n", out_id, name));
        }

        code.push_str("}\n\n");

        // 5. Component instantiation
        if public_inputs.is_empty() {
            code.push_str(&format!("component main = {}Main();\n", self.graph.name));
        } else {
            code.push_str(&format!(
                "component main {{public [{}]}} = {}Main();\n",
                public_inputs.join(", "),
                self.graph.name
            ));
        }

        Ok(code)
    }

    fn wire_name(&self, id: usize) -> String {
        // Find the node to check if it's an input (which uses its label) or intermediate (n_id)
        for node in &self.graph.nodes {
            if node.id == id {
                if node.node_type == NodeType::Input {
                    return node.label.clone();
                } else {
                    return format!("n_{}", id);
                }
            }
        }
        format!("n_{}", id)
    }

    fn generate_inline_range_check(&self, code: &mut String, node_id: usize, x: &str, bits: usize) {
        code.push_str(&format!("    signal bits_{}[{}];\n", node_id, bits));
        code.push_str(&format!("    var sum_{} = 0;\n", node_id));
        code.push_str(&format!("    for (var i = 0; i < {}; i++) {{\n", bits));
        code.push_str(&format!("        bits_{}[i] <-- ({} >> i) & 1;\n", node_id, x));
        code.push_str(&format!("        bits_{}[i] * (1 - bits_{}[i]) === 0;\n", node_id, node_id));
        code.push_str(&format!("        sum_{} += bits_{}[i] * (2 ** i);\n", node_id, node_id));
        code.push_str("    }\n");
        code.push_str(&format!("    {} === sum_{};\n", x, node_id));
        code.push_str(&format!("    n_{} <== 1;\n", node_id));
    }

    pub fn generate_tfhe(&self) -> Result<String, String> {
        let mut code = String::new();

        code.push_str("// Generated by DCL (Differentiable Cryptographic Language) Compiler\n");
        code.push_str("// Backend: Zama tfhe-rs\n\n");
        code.push_str("use tfhe::prelude::*;\n");
        code.push_str("use tfhe::{FheUint64, FheBool, ServerKey};\n\n");

        // We declare the struct containing all inputs
        code.push_str(&format!("pub struct {}Inputs {{\n", self.graph.name));
        for node in &self.graph.nodes {
            if node.node_type == NodeType::Input {
                code.push_str(&format!("    pub {}: FheUint64,\n", node.label));
            }
        }
        code.push_str("}\n\n");

        // The function executes the homomorphic computation graph
        code.push_str(&format!("pub fn {}(\n", self.graph.name.to_lowercase()));
        code.push_str(&format!("    inputs: &{}Inputs,\n", self.graph.name));
        code.push_str("    server_key: &ServerKey,\n");
        code.push_str(") -> FheUint64 {\n");

        let noise_budget = 16.0;
        let mut noise_levels: std::collections::HashMap<usize, f64> = std::collections::HashMap::new();

        for node in &self.graph.nodes {
            match node.node_type {
                NodeType::Input => {
                    noise_levels.insert(node.id, 1.0);
                    code.push_str(&format!("    let n_{} = inputs.{}.clone();\n", node.id, node.label));
                }
                NodeType::Const => {
                    noise_levels.insert(node.id, 0.0);
                    let val_str = node.value.as_deref().unwrap_or("0");
                    let val = val_str.parse::<u64>().unwrap_or_else(|_| {
                        // fallback or modular reduction if needed, but parsing to u64 is standard for FheUint64
                        0
                    });
                    code.push_str(&format!("    let n_{} = FheUint64::try_encrypt_trivial({}, server_key).unwrap();\n", node.id, val));
                }
                NodeType::Add | NodeType::Sub => {
                    let a = node.inputs[0];
                    let b = node.inputs[1];
                    
                    let mut noise_a = *noise_levels.get(&a).unwrap_or(&1.0);
                    let mut noise_b = *noise_levels.get(&b).unwrap_or(&1.0);

                    if noise_a + noise_b > noise_budget {
                        if noise_a >= noise_b {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", a, a));
                            noise_a = 1.0;
                            noise_levels.insert(a, 1.0);
                        } else {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", b, b));
                            noise_b = 1.0;
                            noise_levels.insert(b, 1.0);
                        }
                    }

                    noise_levels.insert(node.id, noise_a + noise_b);
                    let op = if node.node_type == NodeType::Add { "+" } else { "-" };
                    code.push_str(&format!("    let n_{} = &n_{} {} &n_{};\n", node.id, a, op, b));
                }
                NodeType::Mul | NodeType::Div => {
                    let a = node.inputs[0];
                    let b = node.inputs[1];

                    let mut noise_a = *noise_levels.get(&a).unwrap_or(&1.0);
                    let mut noise_b = *noise_levels.get(&b).unwrap_or(&1.0);

                    let mut proj_noise = (noise_a + 1.0) * (noise_b + 1.0);

                    if proj_noise > noise_budget {
                        if noise_a >= noise_b {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", a, a));
                            noise_a = 1.0;
                            noise_levels.insert(a, 1.0);
                        } else {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", b, b));
                            noise_b = 1.0;
                            noise_levels.insert(b, 1.0);
                        }
                        
                        proj_noise = (noise_a + 1.0) * (noise_b + 1.0);
                        
                        if proj_noise > noise_budget {
                            if noise_a > 1.0 {
                                code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", a, a));
                                noise_a = 1.0;
                                noise_levels.insert(a, 1.0);
                            } else {
                                code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", b, b));
                                noise_b = 1.0;
                                noise_levels.insert(b, 1.0);
                            }
                            proj_noise = (noise_a + 1.0) * (noise_b + 1.0);
                        }
                    }

                    noise_levels.insert(node.id, proj_noise);
                    let op = if node.node_type == NodeType::Mul { "*" } else { "/" };
                    code.push_str(&format!("    let n_{} = &n_{} {} &n_{};\n", node.id, a, op, b));
                }
                NodeType::Select => {
                    let cond = node.inputs[0];
                    let t = node.inputs[1];
                    let f = node.inputs[2];
                    
                    let mut noise_cond = *noise_levels.get(&cond).unwrap_or(&1.0);
                    let mut noise_t = *noise_levels.get(&t).unwrap_or(&1.0);
                    let mut noise_f = *noise_levels.get(&f).unwrap_or(&1.0);

                    let mut proj_noise = f64::max(noise_t, noise_f) + noise_cond;
                    if proj_noise > noise_budget {
                        if noise_cond >= noise_t && noise_cond >= noise_f {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", cond, cond));
                            noise_cond = 1.0;
                            noise_levels.insert(cond, 1.0);
                        } else if noise_t >= noise_f {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", t, t));
                            noise_t = 1.0;
                            noise_levels.insert(t, 1.0);
                        } else {
                            code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", f, f));
                            noise_f = 1.0;
                            noise_levels.insert(f, 1.0);
                        }
                        proj_noise = f64::max(noise_t, noise_f) + noise_cond;
                    }

                    noise_levels.insert(node.id, proj_noise);
                    code.push_str(&format!("    let cond_bool_{} = n_{}.eq(1u64);\n", node.id, cond));
                    code.push_str(&format!("    let n_{} = cond_bool_{}.select(&n_{}, &n_{});\n", node.id, node.id, t, f));
                }
                NodeType::IsZero => {
                    let a = node.inputs[0];
                    let mut noise_a = *noise_levels.get(&a).unwrap_or(&1.0);
                    if noise_a + 1.0 > noise_budget {
                        code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", a, a));
                        noise_a = 1.0;
                        noise_levels.insert(a, 1.0);
                    }
                    noise_levels.insert(node.id, noise_a + 1.0);
                    code.push_str(&format!("    let cond_zero_{} = n_{}.eq(0u64);\n", node.id, a));
                    code.push_str(&format!("    let one_const_{} = FheUint64::try_encrypt_trivial(1u64, server_key).unwrap();\n", node.id));
                    code.push_str(&format!("    let zero_const_{} = FheUint64::try_encrypt_trivial(0u64, server_key).unwrap();\n", node.id));
                    code.push_str(&format!("    let n_{} = cond_zero_{}.select(&one_const_{}, &zero_const_{});\n", node.id, node.id, node.id, node.id));
                }
                NodeType::RangeCheck => {
                    let a = node.inputs[0];
                    let mut noise_a = *noise_levels.get(&a).unwrap_or(&1.0);
                    if noise_a + 1.0 > noise_budget {
                        code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", a, a));
                        noise_a = 1.0;
                        noise_levels.insert(a, 1.0);
                    }
                    noise_levels.insert(node.id, noise_a + 1.0);
                    let bits = node.bits.unwrap_or(8);
                    let max_val = (1 << bits) as u64;
                    code.push_str(&format!("    let cond_range_{} = n_{}.lt({}u64);\n", node.id, a, max_val));
                    code.push_str(&format!("    let one_const_{} = FheUint64::try_encrypt_trivial(1u64, server_key).unwrap();\n", node.id));
                    code.push_str(&format!("    let zero_const_{} = FheUint64::try_encrypt_trivial(0u64, server_key).unwrap();\n", node.id));
                    code.push_str(&format!("    let n_{} = cond_range_{}.select(&one_const_{}, &zero_const_{});\n", node.id, node.id, node.id, node.id));
                }
                NodeType::Poseidon => {
                    let a = node.inputs[0];
                    let mut noise_a = *noise_levels.get(&a).unwrap_or(&1.0);
                    if noise_a + 1.0 > noise_budget {
                        code.push_str(&format!("    let n_{} = server_key.bootstrap(&n_{});\n", a, a));
                        noise_a = 1.0;
                        noise_levels.insert(a, 1.0);
                    }
                    noise_levels.insert(node.id, noise_a + 1.0);
                    code.push_str(&format!("    // WARNING: Poseidon is algebraically complex in FHE; using stub\n"));
                    code.push_str(&format!("    let n_{} = n_{}.clone();\n", node.id, node.inputs[0]));
                }
                NodeType::AssertEq | NodeType::AssertBool => {
                    code.push_str(&format!("    // Assertion check node {}\n", node.id));
                }
            }
        }

        if let Some(&out_id) = self.graph.outputs.first() {
            code.push_str(&format!("    n_{}\n", out_id));
        } else {
            code.push_str("    FheUint64::try_encrypt_trivial(0u64, server_key).unwrap()\n");
        }

        code.push_str("}\n");

        Ok(code)
    }
}
